### PR TITLE
Add Authors Functional Tests

### PR DESCRIPTION
**Pull request by KyleMcMaster**
Initial implementation of functional tests for authors endpoints. 

Looking for feedback on how to better test create, update, and delete endpoints.

### CODE REVIEW

**Comment by ardalis** [comment]
See my notes in the issue. Also for test naming:
https://ardalis.com/unit-test-naming-convention

**Comment by KyleMcMaster** [comment]
I updated naming conventions, let me know if there are any additional changes you would like me to make.

**Comment by ardalis** [comment]
These look good, thanks!

**Comment by ardalis** [comment]
Hmm, these tests ran fine locally.

**Pull request merged**
