### PR TITLE
[DO NOT MERGE] v4

### PR DESCRIPTION
**Pull request by maxkoshevoi**
All of the changes that I got for v4 so far. They need to be split into smaller PRs.

This PR is to keep track of what is already merged into `v4` branch.

### CODE REVIEW

**Comment by ardalis** [comment]
Is it save now to merge this?

**Comment by maxkoshevoi** [comment]
@ardalis Totally forgot about this! Everything is already merged. This PR existed to see if I forgot to merge anything from the branch where I did all the changes (they were merged via multiple PRs). But implementation has changed since then, so this PR is no longer relevant.

**Comment by ardalis** [comment]
Great, thanks for clarifying. I'd thought we had already merged the other PRs into the v4 branch... :)

**Comment by maxkoshevoi** [comment]
We did. Everything that was planned to be merged into `v4` is merged in `v4`.

**Pull request closed without merging**
